# Generated by Django 4.0.6 on 2022-08-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='thread_code',
            field=models.CharField(max_length=125),
        ),
    ]
