# Generated by Django 4.1 on 2022-08-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_thread_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
