# Generated by Django 4.1 on 2022-08-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cover_img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
