# Generated by Django 4.1 on 2022-08-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_cover_img_alter_account_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='cover_img',
            field=models.URLField(default='https://firebasestorage.googleapis.com/v0/b/tweeby-6bcd3.appspot.com/o/default_cover.png?alt=media&token=544cd572-0031-4a55-822c-152907ce3a43'),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_img',
            field=models.URLField(default='https://firebasestorage.googleapis.com/v0/b/tweeby-6bcd3.appspot.com/o/default_avatar.png?alt=media&token=c7f99452-f467-4c0f-bd11-68fca7d33803'),
        ),
    ]
