# Generated by Django 4.1 on 2022-08-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_account_email_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email_visible',
        ),
        migrations.AddField(
            model_name='account',
            name='hide_email',
            field=models.BooleanField(default=False),
        ),
    ]
